### ISSUE TITLE
Exception in hermes Consumers 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#820] opened 2017-09-21 08:43 UTC
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class pl.allegro.tech.hermes.consumers.consumer.rate.maxrate.MaxRate]

Version : 0.11.0

**Comment by gamefundas** [comment] 2017-11-17 16:46
Duplicate of #825 
This one can be closed.

**Comment by adamdubiel** [comment] 2017-11-18 08:35
Closing :)

**Closed by adamdubiel** 2017-11-18 08:35 UTC
