### ISSUE TITLE
Hermes Avro support

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#427] opened 2016-03-31 03:54 UTC
I read in the documentation that Avro payload support in Hermes is in incubation phase. What does this really mean, it can be used in production with some limitations or this isn't mature enough for real use.

**Comment by adamdubiel** [comment] 2016-03-31 05:55
We have some production topics using Avro, but there are some non-functional issues with it.

First of all we only support [schemarepo.org](http://schemarepo.org) Schema Repository. We had it deployed internally for our Hadoop infrastructure, but turns out the project looks quite dead and the valid choice at the moment would be to go with Confluent Schema Repo. This is a nuisance though, as coding support for other schema repo is quite easy.

Secondly there is some *magic bytes* logic which we added in 0.8.6, which is not enabled globally and which might need some tuning. The problem is: to properly deserialize Avro you need both writers and readers schema. Prior to 0.8.6 writers schema information was lost once message was published. In 0.8.6 we added support for sending version in Http header, which is than stored in *magic byte* in before serialized Avro data (same approach/spec Camus and Confluent Platform are using [1](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java)). However we need to see if this format and implementation is safe to use. Tests and small scale usage show everything is fine, but there might be some corner cases.

All in all it is incubating because we *might* introduce some breaking changes and would not want to be responsible for breaking someone else production :)

**Comment by gamefundas** [comment] 2016-03-31 15:20
Ok great. So we will also use this in a experimental sort of way to see how it caters to our use cases. I/ my team is new to Avro as well so we may need to understand this a little better. So far we were doing Stomp using ActiveMQ. This is very different than that. For external consumers we would like to have a standard protocol for messages. And Avro kind of fits in perfectly. In the long run hoping to use this feature for sure.
 
Will report back in case we have any trouble running the Avro example.

**Comment by adamdubiel** [comment] 2016-03-31 15:27
Great! There should be no problems as long as you don't change the schemas too much. If you need i can share the "hidden" flag that enables passing schema version in *magic byte* on topics.

**Comment by gamefundas** [comment] 2016-03-31 15:30
That might be helpful if you can share some details on it.

**Comment by adamdubiel** [comment] 2016-03-31 15:52
@wojtkiewicz can you share the flag name and usage? Of course treat it as development feature, we will remove the flag it as soon as we are sure everything works.

**Comment by hikrrish** [comment] 2016-03-31 18:30
Hi, 
I am trying to setup avro schema and followed the documentation, however I am getting below exceptions. As per documentation if you do not specify any schema repository it uses Simple schema store which saves schema in zookeeper. Please let me know if we have to use any flags to specify Simple schema store.


What I have tried:
1) Created an avro topic 
{
    "name": "avrocash",
    "description": "This is my topic",
    "ack": "LEADER",
    "retentionTime": 1,
    "trackingEnabled": false,
    "contentType": "AVRO",
    "validationEnabled": true
}

Created successfully 201

2) Tried to post a schema (Example schema)
 URL: server/topics/com.avrocash/schema
 Updated namespace and name to 
"namespace": "com",
 "name": "avrocash",

failed with "message":"java.net.ConnectException: Connection refused","details":"javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused\n\tat org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:229)\n\tat org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)\n\tat org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)\n\tat org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:228)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)\n\tat org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)\n\tat org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:399)\n\tat org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:303)\n\tat pl.allegro.tech.hermes.infrastructure.schema.repo.JerseySchemaRepoClient.isSubjectRegistered(JerseySchemaRepoClient.java:48)\n\tat pl.allegro.tech.hermes.management.infrastructure.schema.SchemaRepoSchemaSourceRepository.registerSubjectIfNotRegistered(SchemaRepoSchemaSourceRepository.java:23)\n\tat pl.allegro.tech.hermes.management.infrastructure.schema.SchemaRepoSchemaSourceRepository.save(SchemaRepoSchemaSourceRepository.java:17)\n\tat pl.allegro.tech.hermes.management.domain.topic.schema.SchemaSourceService.saveSchemaSource(SchemaSourceService.java:42)\n\tat pl.allegro.tech.hermes.management.api.SchemaEndpoint.save(SchemaEndpoint.java:59)\n\tat sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)\n\tat

**Comment by adamdubiel** [comment] 2016-03-31 20:07
oh, i need to update the docs. This is one of the 'incubation' pitfalls. We actually removed Zookeeper support in 0.8.6, since implementing it in any reasonable way wpuld mean creating a whole new schema repo from scratch. Sorry you had to learn it the hard way :(

**Comment by hikrrish** [comment] 2016-04-24 14:27
@adamdubiel 
I set up the schema -repo rest server and able to successfully post a schema  as described in the documents, appended the metadata section to avro schema. The schema server URL is  http://host/schema-repo for hermes management (got 201 here and verified the schema created on schema-repo server). 

Now I am trying to publish a JSON message(comply to created schema) to this newly created AVRO topic and it is failing  with 
HTTP response code :400
{"message":"javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused Cause: ConnectException: Connection refused","code":"VALIDATION_ERROR"}

schema.repository.type=schema_repo
schema.repository.url=http://host/schema-repo

I have a doubt on sequence of steps, let me know if you have any resolution for this

**Comment by adamdubiel** [comment] 2016-09-22 19:55
We are now working on supporting both schemarepo and Confluent schema repo in Hermes - i'm gonna close this issue, as it is probably outdated by now.

**Closed by adamdubiel** 2016-09-22 19:55 UTC
