### ISSUE TITLE
Using TestContainers for integration testing

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#1072] opened 2019-07-23 12:00 UTC
Hermes uses lots of embedded third party software running for integration testing, including:
kafka, zookeeper, elasticsearch, schema-registry, embedded jms.
We should consider https://www.testcontainers.org/ (or something similar) as an alternative.

What's more we could go even further and build containers of all our modules (frontend, consumers, management) and run them in integration tests in separate JVMs.

**Comment by druminski** [comment] 2019-10-03 13:02
@mareckmareck will work on this one

**Comment by druminski** [comment] 2020-01-28 15:11
This task is available again

**Comment by jewertow** [comment] 2020-10-28 12:31
I was trying to migrate integration tests from embedded third party software to testcontainers, but I give up, because since release of version 1.5.0 `FixedHostPortGenericContainer` will be deprecated. 
Another option is to use `GenericContainer`s, but these containers don't allow to map exposed port to fixed host port and therefore it is not possible to use static configurations in tests. I was trying to do it with `GenericContainer`s and override configuration at runtime, but it was more complex and less clear.
IMHO testcontainers is not a stable solution and probably works well for microservices, but not for large and mature projects like Hermes. I think it would be better to add docker-compose file and execute at startup `Runtime.getRuntime().exec("docker-compose up")` even if it is additional dependency.

**Comment by druminski** [comment] 2020-11-03 19:45
@jewertow thanks for the try, your feedback about this issue is very valuable for us and due to it we will not migrate Hermes integration tests to TestContainers. I’m closing the issue.

**Closed by druminski** 2020-11-03 19:45 UTC
Labels: enhancement, hacktoberfest

**Comment by bsideup** [comment] 2020-11-03 19:57
Uff, sorry to hear that you decided not to use Testcontainers!

> IMHO testcontainers is not a stable solution and probably works well for microservices, but not for large and mature projects like Hermes

Maybe, yeah... It is only used by a few small and young projects like Spring Boot/Framework/Data/Cloud, Quarkus, Micronaut, Akka's Alpakka, Apache Pulsar, JOOQ, Vert.x, Infinispan, Spinnaker, Apache Camel... 😅 

> but I give up, because since release of version 1.5.0 FixedHostPortGenericContainer will be deprecated.
> Another option is to use GenericContainers, but these containers don't allow to map exposed port to fixed host port and therefore it is not possible to use static configurations in tests

There is a reason why we decided to deprecate fixed ports. Consider reading the following article:
https://bsideup.github.io/posts/testcontainers_fixed_ports/

But I respect your decision! 👍

**Comment by jewertow** [comment] 2020-11-03 20:49
> Maybe, yeah... It is only used by a few small and young projects like Spring Boot/Framework/Data/Cloud, Quarkus, Micronaut, Akka's Alpakka, Apache Pulsar, JOOQ, Vert.x, Infinispan, Spinnaker, Apache Camel, and a couple more...

Yeah, that sounds funny... I am aware that you are a Java Champion, but IMHO using testcontainers in case of Hermes whithout fixed port mapping makes these integration tests **more complex**, because it is necessary to override configuration at runtime. 

> There is a reason why we decided to deprecate fixed ports. Consider reading the following article:
https://bsideup.github.io/posts/testcontainers_fixed_ports/

I am aware of possibility of ports conflict, but when tests runs in an isolated environment it is not a problem. 
So please don't be upset that I don't want to use your library.

P.S.
Additionally when I was running Hermes tests with testcontainers, gradle sometimes (indeterministically) was getting stuck. 

Best regards,
Jacek

**Comment by bsideup** [comment] 2020-11-03 20:54
> Additionally when I was running Hermes tests with testcontainers, gradle sometimes (indeterministically) was getting stuck.

Since this is the first time I hear about Testcontainers affecting Gradle, I get a feeling that it is just a random statement to make your arguments sound more dramatic. Happy to be wrong (extra points for reporting an issue to Testcontainers and/or Gradle, btw)

Oh, and I am just a random community guy, my JC status means nothing here. Although maybe I got it for collaborating with people, not fighting them, so I am out of this conversation, it is your choice anyways and I have no intention of forcing you to use the library, just wanted other maintainers of Hermes to see the other side of the coin of this "research" :)

**Comment by jewertow** [comment] 2020-11-03 21:00
Ok, if you really want, I can reproduce the problem and push a problematic branch to my fork.
So I will ping you in a few days to debug the code.

**Comment by druminski** [comment] 2020-11-06 08:21
@bsideup @jewertow Thank you very much for your answers in this thread. Few clarification notes from me as a Hermes maintainer:

1. In this task we planned to switch over 200 integration tests to Testcontainers.
2. The task has a `nice to have` status, as we are satisfied with the stability of current integration tests.
3. The task was opened for over a year and a half. During this time, two contributors tried to do this task in their spare time and I really appreciate their efforts.
4. So far, the task has not been completed as the switch of these 200 integration tests to Testcontainers is not a trivial task and requires more attention.
5. I closed the task, but it doesn't mean we won't come back to it. Especially @bsideup after seeing your arguments.
6. We use Testcontainers ourselves in many projects. Even in Hermes we’ve been using it for a while too already. It just so happens that @jewertow was the first contributor who [implemented](https://github.com/allegro/hermes/pull/1127/files) use of Testcontainers in a few Hermes functionality tests. However, switching 200 Hermes integration tests at once to Testcontainers is not a trivial task as can be seen from the history of this thread. Therefore, as I mentioned, it’s possible that we will return to this task, but this time I will recommend to switch individual integration tests, not all of them at once. If this approach works, we will gradually switch over to Testcontainers.
7. I’m also curious what will come out from reproduction of the error that @jewertow mentioned. @jewertow good luck @bsideup it would be awesome if you could find some time to help @jewertow with the debugging.

Once again, thank you for your support and contribution to the Hermes project.
