### ISSUE TITLE
Avoid clearing unsaved topic/subscription forms

### ISSUE THREAD

**Issue by faderskd** [allegro/hermes#954] opened 2018-11-08 13:23 UTC
When you fill in topic/subscription form, not save it and click outside the form modal, input data is cleared and you have to do all the work from the beginning. We want to keep the input in form when it is closed (accidentally or deliberately).

**Comment by krzysztofpcy** [comment] 2019-10-24 10:02
#1135

**Comment by druminski** [comment] 2020-09-02 12:25
Reported pull request didn’t work as expected, so I closed it and the issue is still open and available.

**Comment by pwolaq** [comment] 2020-10-01 08:29
Hello, I would like to try to fix it :)

**Closed** 2021-02-03 11:31 UTC
Labels: hacktoberfest
