### ISSUE TITLE
NullPointer Exception in Frontend 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#672] opened 2016-12-16 13:51 UTC
java.lang.NullPointerException: null
        at pl.allegro.tech.hermes.frontend.blacklist.BlacklistZookeeperNotifyingCache.childEvent(BlacklistZookeeperNotifyingCache.java:27)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:513)
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:773)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

**Comment by adamdubiel** [comment] 2016-12-16 13:53
What did you do to get this result? Blacklisting topic?

**Comment by hikrrish** [comment] 2016-12-16 13:56
We have not tried blacklisting any topic, though I see below exception in zookeeper node:
caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x9758c21b496d000b

**Comment by adamdubiel** [comment] 2016-12-16 14:02
Hmm this looks like some kind of connectivity problem - do you have any connection errors in Hermes logs?

**Comment by hikrrish** [comment] 2016-12-16 15:37
I can see the  client sessionid 0x9758c21b496d000b is actually belongs to one of frontend node. This is the only error level statement I can find frontend logs. Just before the exception, it prints 
2016-12-14 01:17:45.660 DEBUG c.n.config.AbstractPollingScheduler - Polling started
2016-12-14 01:18:18.725 INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
So yes there is a network disruption

**Comment by adamdubiel** [comment] 2016-12-16 15:43
Yes, looks like it. The exception you got occurred when trying to refresh one of caches so we needed to log it. But the root cause was losing the connection. Nothing to fix here, so i'm closing the issue.

**Closed by adamdubiel** 2016-12-16 15:43 UTC
