### ISSUE TITLE
Increasing number of missing proccesses

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#573] opened 2016-09-14 09:08 UTC
From time to time in new consumers we observe increasing number of missing processes. Missing processes is a metric named:

`consumer.*.consumers-workload.monitor.missing.count`

Problem visualization:
<img width="1319" alt="screen shot 2016-09-14 at 10 58 09" src="https://cloud.githubusercontent.com/assets/4473056/18506177/f3f4e564-7a6a-11e6-8dfb-93221d44400e.png">

Hints:
~~Metrics in `ConsumersRuntimeMonitor` class should be type of gauge instead of counter.~~

**Comment by adamdubiel** [comment] 2016-09-14 09:17
This is not a bug and those metrics show the truth. Gauge will not be a good measure here.

How gauge works? It reports current value, where current is "at time of sending reporting to metric store". We can't predict when will it happen, so most of the times it will report 0.

Why counter? Because values are good at any point in time and using some magic, they can be presented as if it was a meter.

So if you took a look at the metric behind the screenshot, you would see:

```
aliasSub(aliasByNode(summarize(nonNegativeDerivative(hermes.consumer.*.consumers-workload.monitor.missing.count), '2m'), 4), '(.*)', '\1 missing processes')
```

Counter is only increased. To see the changes we count the derivative (change in time), which is then summed in 2m window. So if we need to tune something, tune the metric query, but the counter itself is not a bug.

**Comment by druminski** [comment] 2016-09-14 09:46
Ok, I see now that this metric needs a special treatment. I didn't notice that we already calculate the derivative, so actually we don't have a problem with the metric but with missing consumer processes?

**Comment by adamdubiel** [comment] 2016-09-14 09:51
Yep, as can be seen in logs. Closing.

**Closed by adamdubiel** 2016-09-14 09:51 UTC
Labels: bug
