### ISSUE TITLE
[KAFKA-4669] Correlation id for response () does not match request ()

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#819] opened 2017-09-15 08:51 UTC
Recently one of our hermes-frontend instances thrown lot of exceptions this type:

```
java.lang.IllegalStateException: Correlation id for response (475734766) does not match request (475734763)
	at org.apache.kafka.clients.NetworkClient.correlate(NetworkClient.java:486)
	at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:381)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:229)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:134)
	at java.lang.Thread.run(Thread.java:745)
```

Restart of the instance helped as these exceptions stopped being thrown.

Mentioned exceptions probably are related to [KAFKA-4669 bug](https://issues.apache.org/jira/browse/KAFKA-4669) and because of this we should update kafka-producer in Hermes to version 0.11.0.1 which fixes it.

**Comment by adamdubiel** [comment] 2018-10-19 13:44
Closing as a duplicate of #914 .

**Closed by adamdubiel** 2018-10-19 13:44 UTC
Labels: bug
